[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan storage:link || true && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
